CREATE TABLE IF NOT EXISTS public.sdo_student_records (
  record_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_number text NOT NULL,
  offense_type text NOT NULL,
  offense_incident_date date NULL,
  case_reference_number text NULL,
  remarks text NULL,
  source_file_name text NULL,
  recorded_by text NULL,
  record_fingerprint text NOT NULL UNIQUE,
  is_archived boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sdo_student_records_student
  ON public.sdo_student_records (student_number);

CREATE INDEX IF NOT EXISTS idx_sdo_student_records_incident_date
  ON public.sdo_student_records (offense_incident_date DESC);

INSERT INTO public.sdo_student_records (
  student_number,
  offense_type,
  offense_incident_date,
  source_file_name,
  record_fingerprint
)
SELECT
  smr.student_number,
  smr.offense_type,
  smr.offense_incident_date,
  'Legacy SDO registry data',
  md5(
    coalesce(smr.student_number, '') || '|' ||
    lower(trim(coalesce(smr.offense_type, ''))) || '|' ||
    coalesce(smr.offense_incident_date::text, '') || '|'
  )
FROM public.student_master_records smr
WHERE coalesce(smr.has_disciplinary_action, false) = true
  AND nullif(trim(coalesce(smr.student_number, '')), '') IS NOT NULL
  AND nullif(trim(coalesce(smr.offense_type, '')), '') IS NOT NULL
ON CONFLICT (record_fingerprint) DO NOTHING;

ALTER TABLE public.sdo_student_records ENABLE ROW LEVEL SECURITY;
