const express = require('express');
const router = express.Router();
const messageController = require('../controllers/messageController');
const messageHistoryController = require('../controllers/messageHistoryController');
const formerRoomHistoryController = require('../controllers/formerRoomHistoryController');
const groupRemovalController = require('../controllers/groupRemovalController');
const roomAdminController = require('../controllers/roomAdminController');
const { protect } = require('../middleware/authMiddleware');
const { authorizeRoleGroup } = require('../middleware/rbacMiddleware');
router.use(protect, authorizeRoleGroup('ALL_STAFF'));
router.get('/unread-count', messageController.getUnreadCount);
router.get('/thread', messageController.getThread);
router.post('/thread', messageController.sendThreadMessage);
router.patch('/thread/read', messageController.markThreadRead);
router.get('/members/scholars', messageController.getScholarMembers);
router.get('/members/contacts', messageController.getMessagingContacts);
router.get('/archived', messageController.getArchivedThreads);
router.get('/former-rooms', formerRoomHistoryController.listFormerRooms);
router.get('/former-rooms/:roomId/window', formerRoomHistoryController.getFormerRoomWindow);
router.get('/message/:messageId/history', messageController.getMessageEditHistory);
router.patch('/message/:messageId/unsend', messageController.unsendMessage);
router.patch('/message/:messageId', messageController.editMessage);
router.delete('/message/:messageId', messageController.hideMessageForMe);
router.get('/conversations', messageController.getConversations);
router.get('/conversations/:counterpartyId', messageHistoryController.getConversationMessages);
router.get('/conversations/:counterpartyId/messages', messageHistoryController.getConversationMessages);
router.post('/conversations/:counterpartyId', messageController.sendMessage);
router.post('/conversations/:counterpartyId/messages', messageController.sendMessage);
router.patch('/conversations/:counterpartyId/read', messageController.markConversationRead);
router.patch('/conversations/:counterpartyId/unread', messageController.markConversationUnread);
router.patch('/conversations/:counterpartyId/read-state', messageController.setConversationReadState);
router.patch('/conversations/:counterpartyId/archive', messageController.archiveConversation);
router.patch('/conversations/:counterpartyId/restore', messageController.restoreConversation);
router.get('/rooms', messageController.getRooms);
router.post('/rooms', messageController.createRoom);
router.get('/rooms/:roomId/messages', messageHistoryController.getRoomMessages);
router.post('/rooms/:roomId/messages', messageController.sendRoomMessage);
router.get('/rooms/:roomId/members', messageController.getRoomMembers);
router.post('/rooms/:roomId/members', roomAdminController.manageRoomAdminRole, groupRemovalController.removeMember, messageController.addRoomMembers);
router.delete('/rooms/:roomId/members/:memberId', groupRemovalController.removeMember);
router.delete('/rooms/:roomId/leave', messageController.leaveRoom);
router.post('/rooms/:roomId/leave', messageController.leaveRoom);
router.patch('/rooms/:roomId/read', messageController.markRoomMessagesRead);
router.patch('/rooms/:roomId/unread', messageController.markRoomMessagesUnread);
router.patch('/rooms/:roomId/read-state', messageController.setRoomReadState);
router.patch('/rooms/:roomId/archive', messageController.archiveRoom);
router.patch('/rooms/:roomId/restore', messageController.restoreRoom);
module.exports = router;
